#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if test -f "/data/simple_drf.sqlite3"; then
  now=$(date +%Y%m%dT%H%M)
  sqlite3 /data/simple_drf.sqlite3 ".backup /data/simple_drf-$now.sqlite3"
fi

python manage.py migrate

exec gunicorn simple_drf.wsgi
